// examples/react/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  constructor(props) {
    super(props);

    this.ref = React.createRef();
    this.state = {
      userId: 'calmery',
      value: '',
      disabled: false
    };
  }

  componentDidMount() {
    this.ref.current.addEventListener('load', this._onLoad.bind(this));
    this.ref.current.addEventListener('error', this._onError.bind(this));
  }

  render() {
    const { userId, value, disabled } = this.state;

    return (
      <div className='App'>
        <header className='App-header'>
          <img src={logo} className='App-logo' alt='logo' />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className='App-link'
            href='https://reactjs.org'
            target='_blank'
            rel='noopener noreferrer'
          >
            Learn React
          </a>
          <elm-qiita-profile
            ref={this.ref}
            data-user-id={userId}
            onLoad={this._onLoad.bind(this)}
          />
          <div>
            <input
              type='text'
              value={value}
              disabled={disabled}
              onChange={this._onChange.bind(this)}
            />
            <button disabled={disabled} onClick={this._onClick.bind(this)}>
              Get
            </button>
          </div>
        </header>
      </div>
    );
  }

  _onLoad() {
    this.setState({ disabled: false });
  }

  _onError() {
    this.setState({ disabled: false });
  }

  // Input

  _onChange(event) {
    this.setState({ value: event.target.value });
  }

  // Button

  _onClick() {
    const { value } = this.state;

    this.setState({
      disabled: true,
      userId: value,
      value: ''
    });
  }
}

export default App;

// examples/vue/src/App.vue
<template>
  <div id='app'>
    <img src='./assets/logo.png' />
    <HelloWorld />
    <elm-qiita-profile ref='elm' v-bind:data-user-id='userId' />
    <div>
      <input v-model='value' v-bind:disabled='disabled' />
      <button @click='onClick' v-bind:disabled='disabled'>Get</button>
    </div>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld';

export default {
  name: 'App',
  components: {
    HelloWorld
  },
  data() {
    return {
      userId: 'calmery',
      value: '',
      disabled: false
    };
  },
  mounted: function() {
    const elm = this.$refs.elm;

    elm.addEventListener('load', this._onLoad.bind(this));
    elm.addEventListener('error', this._onError.bind(this));
  },
  methods: {
    onClick: function() {
      if (this.value === '') {
        return;
      }

      this.userId = this.value;
      this.value = '';
      this.disabled = true;
    },
    _onLoad: function() {
      this.disabled = false;
    },
    _onError: function() {
      this.disabled = false;
    }
  }
};
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
