// examples/react/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  constructor(props) {
    super(props);

    this.ref = React.createRef();
    this.state = {
      userId: 'calmery',
      value: '',
      disabled: false
    };
  }

  componentDidMount() {
    this.ref.current.addEventListener('load', this._onLoad.bind(this));
    this.ref.current.addEventListener('error', this._onError.bind(this));
  }

  render() {
    const { userId, value, disabled } = this.state;

    return (
      <div className='App'>
        <header className='App-header'>
          <img src={logo} className='App-logo' alt='logo' />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className='App-link'
            href='https://reactjs.org'
            target='_blank'
            rel='noopener noreferrer'
          >
            Learn React
          </a>
          <elm-qiita-profile
            ref={this.ref}
            data-user-id={userId}
            onLoad={this._onLoad.bind(this)}
          />
          <div>
            <input
              type='text'
              value={value}
              disabled={disabled}
              onChange={this._onChange.bind(this)}
            />
            <button disabled={disabled} onClick={this._onClick.bind(this)}>
              Get
            </button>
          </div>
        </header>
      </div>
    );
  }

  _onLoad() {
    this.setState({ disabled: false });
  }

  _onError() {
    this.setState({ disabled: false });
  }

  // Input

  _onChange(event) {
    this.setState({ value: event.target.value });
  }

  // Button

  _onClick() {
    const { value } = this.state;

    this.setState({
      disabled: true,
      userId: value,
      value: ''
    });
  }
}

export default App;

// examples/angular/src/app/app.component.ts
import { Component, ViewChild, AfterViewInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements AfterViewInit {
  @ViewChild('elm') ref;

  title = 'angular';

  public userId = 'calmery';
  public value = '';
  public disabled = false;

  ngAfterViewInit() {
    const elm = this.ref.nativeElement;

    elm.addEventListener('load', this._onLoad.bind(this));
    elm.addEventListener('error', this._onError.bind(this));
  }

  public onChange(event) {
    this.value = event.target.value;
  }

  public onClick() {
    this.userId = this.value;
    this.value = '';
    this.disabled = true;
  }

  private _onLoad() {
    this.disabled = false;
  }

  private _onError() {
    this.disabled = false;
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
  <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
</div>
<h2>Here are some links to help you start: </h2>
<ul>
  <li>
    <h2><a target="_blank" rel="noopener" href="https://angular.io/tutorial">Tour of Heroes</a></h2>
  </li>
  <li>
    <h2><a target="_blank" rel="noopener" href="https://angular.io/cli">CLI Documentation</a></h2>
  </li>
  <li>
    <h2><a target="_blank" rel="noopener" href="https://blog.angular.io/">Angular blog</a></h2>
  </li>
  <elm-qiita-profile #elm attr.data-user-id="{{ userId }}"></elm-qiita-profile>
  <div>
    <input type="text" value="{{ value }}" (change)="onChange($event)" [disabled]="disabled" />
    <button (click)="onClick()" [disabled]="disabled">Get</button>
  </div>
</ul>
